### ISSUE TITLE
Not Able to Scroll on Settings Page

### ISSUE THREAD

**Issue by mtwn105** [nfuad/HeroForm#8]
Not able to scroll on settings page of a form

Screen Res - 1366 x 768

![image](https://user-images.githubusercontent.com/12975481/180225645-2ecaa0ed-3e76-4f88-944c-f7e381a5f154.png)

**Comment by nfuad** [comment]
Hey, thanks for checking out the project! We still haven't been able to make all the screens responsive, we'll definitely try to take this one into account in the next iteration.

**Comment by nfuad** [comment]
Hey this problem is fixed now. Closing the issue. Thanks for checking it out btw!
